package es.uniovi.reflection.progquery.database.relations;

public enum ASTRelationTypes implements RelationTypesInterface {
	/*Compilation Unit to AST Node*/
	CU_ENCLOSES, CU_IMPORTS,

	/*Type Definition to Definition U Block*/
	COMPONENT_ACCESSOR, COMPONENT_FIELD,
	DECLARES_COMPONENT,
	DECLARES_FIELD, DECLARES_METHOD, DECLARES_CONSTRUCTOR,
	DECLARES_TYPE, //Also for CUs
	ENUM_DECLARES_ELEMENT, TYPE_STATIC_INIT,

	/*Type Definition to AST Type*/
	EXTENDS_CLAUSE, IMPLEMENTS_CLAUSE, TYPE_HAS_TYPE_PARAM,

	/*Annotations*/
	HAS_ANNOTATION, ANNOTATION_ARG, ANNOTATION_NAME,

	/*Callable Definition to AST Node*/
	CALLABLE_BODY, CALLABLE_PARAM, CALLABLE_THROWS, CALLABLE_TYPE_PARAM,
	DEFAULT_VALUE,
	METHOD_RETURN_TYPE,
	RECEIVER_PARAM,

	/*AST Type to AST Type*/
	AST_ARRAY_ELEMENT_TYPE,
	AST_INTERSECTION_OF,
	AST_TYPE_ARG, PARAMETERIZES_AST_TYPE,
	AST_TYPE_PARAM_EXTENDS,
	AST_UNION_ALTERNATIVE,
	UNDERLYING_AST_TYPE,
	WILDCARD_BOUND,

	/*Statement(Part?) to Statement*/
	BLOCK_ENCLOSES,
	CASE_STATEMENT,
	CATCH_BLOCK, CATCH_VARIABLE,
	DO_WHILE_STATEMENT,
	FOREACH_STATEMENT, FOREACH_VAR,
	FOR_LOOP_INIT, FOR_LOOP_STATEMENT, FOR_LOOP_UPDATE /*Expression statement*/,
	IF_ELSE, IF_THEN,
	LABELED_STATEMENT_ENCLOSES,
	SWITCH_CASE,
	SYNCHRONIZED_BLOCK,
	TRY_BLOCK, TRY_CATCH, TRY_FINALLY, TRY_RESOURCES,
	VAR_DEC_INIT,
	WHILE_STATEMENT,

	/*Statement(Part?) to Expression*/
	ASSERT_CONDITION, ASSERT_DETAIL,
	CASE_EXPR,
	DO_WHILE_CONDITION,
	ENCLOSES_EXPR,
	FOREACH_EXPR, FOR_LOOP_CONDITION,
	INITIALIZATION_EXPR, //Initialization to Expression
	IF_CONDITION,
	RETURN_EXPR,
	SWITCH_EXPR,
	SYNCHRONIZED_EXPR,
	THROW_EXPR,
	WHILE_CONDITION,

	/*Variable declaration to AST Type*/
	COMPONENT_TYPE,
	VAR_DEC_TYPE,


	/*Lambda Expression to Statement U Parameter*/
	LAMBDA_BODY, LAMBDA_PARAM,

	/*Expression to AST Type*/
	CALLABLE_REFERENCE_TYPE_ARG,
	CAST_TYPE, INSTANCE_OF_TYPE,
	INVOCATION_TYPE_ARG,
	NEW_INSTANCE_BODY, NEW_INSTANCE_NAME, NEW_INSTANCE_TYPE_ARG,
	NEW_ARRAY_TYPE,

	/*Expression to Expression*/
	ARRAY_ACCESS_EXPR, ARRAY_ACCESS_INDEX,
	ASSIGNMENT_LHS, ASSIGNMENT_RHS,
	BINARY_OP_LHS, BINARY_OP_RHS, BINARY_OP_COND_RHS,
	CALLABLE_REFERENCE_QUALIFIER,
	CAST_EXPR,
	COMPOUND_ASSIGNMENT_LHS, COMPOUND_ASSIGNMENT_RHS,
	CONDITIONAL_EXPR_CONDITION, CONDITIONAL_EXPR_ELSE, CONDITIONAL_EXPR_THEN,
	ERRONEOUS_CAUSED_BY,
	INSTANCE_OF_EXPR,
	IDENT_SELECTION_FROM,
	INVOCATION_ARG, INVOCATION_METHOD_SELECTION,
	NEW_ARRAY_DIMENSION, NEW_ARRAY_INIT,
	NEW_INSTANCE_ARG, NEW_INSTANCE_ENCLOSING_EXPR,
	UNARY_OPERAND
}
