package es.uniovi.reflection.progquery.database.relations;

public enum PGRelationTypes implements RelationTypesInterface {
	DEPENDS_ON_PACKAGE,
	DEPENDS_ON_EXTERNAL_PACKAGE,
	PACKAGE_INCLUDES_CU,
	PROGRAM_DECLARES_PACKAGE,

	PROGRAM_DECLARES_MODULE,
	MODULE_CONTAINS_PACKAGE, MODULE_INFO_FILE,

	MODULE_EXPORTS,
	MODULE_OPENS,
	MODULE_PROVIDES,
	EXPORTS_PACKAGE, EXPORTS_ONLY_TO,
	OPENS_PACKAGE, OPENS_ONLY_TO,
	PROVIDES_SERVICE, PROVIDES_IMPL,
	MODULE_REQUIRES,
	MODULE_USES_SERVICE
}
