package es.uniovi.reflection.progquery.database.relations;

public enum TypeRelations implements RelationTypesInterface {
    INHERITS_FIELD, INHERITS_METHOD,
    EXTENDS_CLASS, IMPLEMENTS_INTERFACE,
    PERMITS_SUBTYPE,
    OVERRIDES,

    INFERRED_TYPE, ITS_TYPE_IS, REFERS_TO_TYPE,

    ARRAY_ELEMENT_TYPE,
    GENERIC_TYPE_PARAM, PARAMETERIZES_TYPE, TYPE_ARGUMENT,
    PARAM_TYPE, RECEIVER_TYPE, RETURN_TYPE, THROWS_TYPE,
    WILDCARD_EXTENDS_BOUND, WILDCARD_SUPER_BOUND,
    INTERSECTION_OF, UNION_ALTERNATIVE,
    LOWER_BOUND_TYPE, UPPER_BOUND_TYPE
}
